### PR TITLE
Fix CLI command and Improve Python readability

### PR DESCRIPTION
**Pull request by berndverst**
The previous Azure CLI command for obtaining the master key is being deprecated.

Python samples were not very readable. I improved the style (indentation, line breaks) for readability.

### CODE REVIEW

**Comment by berndverst** [comment]
FYI @deborahc @moderakh

**Comment by deborahc** [comment]
@berndverst - thank you for the contribution! The changes look good to me. Adding @southpolesteve  to take a look and help merge it in.

**Comment by berndverst** [comment]
By the way, I assume some of this will change soon? I've been using azure-cosmos 4.0.0b6 which has a rather different SDK

**Comment by southpolesteve** [comment]
Thanks @berndverst! We just shipped 4.0.0 today which is nearly the same as the beta. What you see on master is the latest.

**Comment by southpolesteve** [comment]
Thanks, @berndverst! We did GA our v4 SDK this week which lives here https://github.com/Azure/azure-sdk-for-python. Further SDK development will happen in that repo. I'll be cleaning up this one soon and semi-archiving it.

**Pull request merged**
